### ISSUE TITLE
Random redirect to admin-ajax.php

### ISSUE THREAD

**Issue by tannerm** [NEU-Libraries/northeasterncommons#10]
Sometimes the site will spit you out to admin-ajax.php showing a blank page with a "0".

**Comment by dustyf** [comment]
I just got the admin-ajax redirect on my local and it is, in fact, because of that cookie that is being set.  the cookie name is 'redirect_to'

![image](https://user-images.githubusercontent.com/517178/49982127-acec3e00-ff20-11e8-86de-18eee1e723cb.png)

**Comment by tannerm** [comment]
This was resolved with the cookie redirect issue.
