### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by dustyf** [NEU-Libraries/northeasterncommons#14]

**Comment by dustyf** [comment]
Login Scenarios


NU Commons
    Shibboleth

GSE Network
    Shibboleth
    Twitter
    Google
    Local Login

PhD Network
    Shibboleth

I'm guessing we can have separate login screens - one for each network

**Comment by PatrickYott** [comment]
I think the only login screen we need is for the GSE Network.  Since both the PhD and NU Commons are shib only, can't the login button take us directly to our Shib IDP?
